sudo: false
language: node_js
node_js: '6'
cache:
  directories:
    - node_modules
    - "$HOME/.electron"
    - /Library/Caches/Homebrew
    - $HOME/.npm
os:
  - osx
  - linux

addons:
  apt:
    sources:
      - deadsnakes
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
      - rpm
      - bsdtar
      - icnsutils
      - gcc-4.9
      - gcc-multilib
      - g++-multilib
      - graphicsmagick
      - rpm
      - xz-utils

notifications:
  email: false
before_script:
- npm prune
after_success:
- bash -x ./perform_ci_build.sh
branches:
  only:
  - master
