branches:
  only:
    - master

version: 1.0.{build}

platform:
  - x64
cache:
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input
  - git config --global user.email "christianalfoni@gmail.com"
  - git config --global user.name "Christian Alfoni"

environment:
  GH_TOKEN:
    secure: f7JcLMFYeXPM3PzwuvdkyJAHaq4gSEZo4X6cicLG1WShNe1CDKPiRXnT27e/t5Gf

install:
  - ps: Install-Product node 8 x64
  - set CI=true
  - npm install

build_script:
  - if "%APPVEYOR_REPO_BRANCH%"=="master" if "%APPVEYOR_PULL_REQUEST_NUMBER%"=="" set PUBLISH=true
  - if defined PUBLISH npm run build
  - if defined PUBLISH npm run package:win -- --publish=always

test: off
